spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

jpa:
hibernate:
  ddl-auto: create
properties:
  hibernate:
format-sql: true
use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug